
TOPLEVEL_LANG = verilog
TOPLEVEL := axi_stream_pipeline

#COMPILE_ARGS=-pfileline=1

# top level source files
VERILOG_SOURCES = $(NF_DESIGN_DIR)/hw/hdl/axi_stream_pipeline/axi_stream_pipeline.v

MODULE := test_axi_stream_pipeline

include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim

